// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _p_G1_HH_
#define _p_G1_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct p_G1 : public sc_module {
    // Port declarations 3
    sc_out< sc_logic > ap_ready;
    sc_in< sc_lv<32> > x;
    sc_out< sc_lv<32> > ap_return;


    // Module declarations
    p_G1(sc_module_name name);
    SC_HAS_PROCESS(p_G1);

    ~p_G1();

    sc_trace_file* mVcdFile;

    sc_signal< sc_lv<17> > tmp_371_fu_38_p1;
    sc_signal< sc_lv<15> > tmp_i_fu_28_p4;
    sc_signal< sc_lv<19> > tmp_372_fu_60_p1;
    sc_signal< sc_lv<13> > tmp_i1_fu_50_p4;
    sc_signal< sc_lv<22> > tmp_s_fu_72_p4;
    sc_signal< sc_lv<32> > tmp_38_fu_82_p1;
    sc_signal< sc_lv<32> > tmp_49_i3_fu_64_p3;
    sc_signal< sc_lv<32> > tmp_fu_86_p2;
    sc_signal< sc_lv<32> > tmp_49_i_fu_42_p3;
    static const sc_logic ap_const_logic_1;
    static const bool ap_const_boolean_1;
    static const sc_lv<32> ap_const_lv32_11;
    static const sc_lv<32> ap_const_lv32_1F;
    static const sc_lv<32> ap_const_lv32_13;
    static const sc_lv<32> ap_const_lv32_A;
    static const sc_logic ap_const_logic_0;
    // Thread declarations
    void thread_ap_ready();
    void thread_ap_return();
    void thread_tmp_371_fu_38_p1();
    void thread_tmp_372_fu_60_p1();
    void thread_tmp_38_fu_82_p1();
    void thread_tmp_49_i3_fu_64_p3();
    void thread_tmp_49_i_fu_42_p3();
    void thread_tmp_fu_86_p2();
    void thread_tmp_i1_fu_50_p4();
    void thread_tmp_i_fu_28_p4();
    void thread_tmp_s_fu_72_p4();
};

}

using namespace ap_rtl;

#endif
