// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "p_Ma.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic p_Ma::ap_const_logic_1 = sc_dt::Log_1;
const bool p_Ma::ap_const_boolean_1 = true;
const sc_logic p_Ma::ap_const_logic_0 = sc_dt::Log_0;

p_Ma::p_Ma(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_ready);

    SC_METHOD(thread_ap_return);
    sensitive << ( tmp_s_fu_32_p2 );
    sensitive << ( tmp_36_fu_38_p2 );

    SC_METHOD(thread_tmp_36_fu_38_p2);
    sensitive << ( y );
    sensitive << ( z );

    SC_METHOD(thread_tmp_fu_26_p2);
    sensitive << ( y );
    sensitive << ( z );

    SC_METHOD(thread_tmp_s_fu_32_p2);
    sensitive << ( x );
    sensitive << ( tmp_fu_26_p2 );

    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "p_Ma_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, x, "(port)x");
    sc_trace(mVcdFile, y, "(port)y");
    sc_trace(mVcdFile, z, "(port)z");
    sc_trace(mVcdFile, ap_return, "(port)ap_return");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, tmp_fu_26_p2, "tmp_fu_26_p2");
    sc_trace(mVcdFile, tmp_s_fu_32_p2, "tmp_s_fu_32_p2");
    sc_trace(mVcdFile, tmp_36_fu_38_p2, "tmp_36_fu_38_p2");
#endif

    }
}

p_Ma::~p_Ma() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void p_Ma::thread_ap_ready() {
    ap_ready = ap_const_logic_1;
}

void p_Ma::thread_ap_return() {
    ap_return = (tmp_s_fu_32_p2.read() ^ tmp_36_fu_38_p2.read());
}

void p_Ma::thread_tmp_36_fu_38_p2() {
    tmp_36_fu_38_p2 = (z.read() & y.read());
}

void p_Ma::thread_tmp_fu_26_p2() {
    tmp_fu_26_p2 = (z.read() ^ y.read());
}

void p_Ma::thread_tmp_s_fu_32_p2() {
    tmp_s_fu_32_p2 = (tmp_fu_26_p2.read() & x.read());
}

}

