// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "p_S0.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic p_S0::ap_const_logic_1 = sc_dt::Log_1;
const bool p_S0::ap_const_boolean_1 = true;
const sc_lv<32> p_S0::ap_const_lv32_2 = "10";
const sc_lv<32> p_S0::ap_const_lv32_1F = "11111";
const sc_lv<32> p_S0::ap_const_lv32_D = "1101";
const sc_lv<32> p_S0::ap_const_lv32_16 = "10110";
const sc_logic p_S0::ap_const_logic_0 = sc_dt::Log_0;

p_S0::p_S0(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_ready);

    SC_METHOD(thread_ap_return);
    sensitive << ( tmp_fu_96_p2 );
    sensitive << ( tmp_49_i3_fu_66_p3 );

    SC_METHOD(thread_tmp_368_fu_40_p1);
    sensitive << ( x );

    SC_METHOD(thread_tmp_369_fu_62_p1);
    sensitive << ( x );

    SC_METHOD(thread_tmp_370_fu_84_p1);
    sensitive << ( x );

    SC_METHOD(thread_tmp_49_i3_fu_66_p3);
    sensitive << ( tmp_369_fu_62_p1 );
    sensitive << ( tmp_i1_fu_52_p4 );

    SC_METHOD(thread_tmp_49_i6_fu_88_p3);
    sensitive << ( tmp_370_fu_84_p1 );
    sensitive << ( tmp_i4_fu_74_p4 );

    SC_METHOD(thread_tmp_49_i_fu_44_p3);
    sensitive << ( tmp_368_fu_40_p1 );
    sensitive << ( tmp_i_fu_30_p4 );

    SC_METHOD(thread_tmp_fu_96_p2);
    sensitive << ( tmp_49_i_fu_44_p3 );
    sensitive << ( tmp_49_i6_fu_88_p3 );

    SC_METHOD(thread_tmp_i1_fu_52_p4);
    sensitive << ( x );

    SC_METHOD(thread_tmp_i4_fu_74_p4);
    sensitive << ( x );

    SC_METHOD(thread_tmp_i_fu_30_p4);
    sensitive << ( x );

    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "p_S0_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, x, "(port)x");
    sc_trace(mVcdFile, ap_return, "(port)ap_return");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, tmp_368_fu_40_p1, "tmp_368_fu_40_p1");
    sc_trace(mVcdFile, tmp_i_fu_30_p4, "tmp_i_fu_30_p4");
    sc_trace(mVcdFile, tmp_369_fu_62_p1, "tmp_369_fu_62_p1");
    sc_trace(mVcdFile, tmp_i1_fu_52_p4, "tmp_i1_fu_52_p4");
    sc_trace(mVcdFile, tmp_370_fu_84_p1, "tmp_370_fu_84_p1");
    sc_trace(mVcdFile, tmp_i4_fu_74_p4, "tmp_i4_fu_74_p4");
    sc_trace(mVcdFile, tmp_49_i_fu_44_p3, "tmp_49_i_fu_44_p3");
    sc_trace(mVcdFile, tmp_49_i6_fu_88_p3, "tmp_49_i6_fu_88_p3");
    sc_trace(mVcdFile, tmp_fu_96_p2, "tmp_fu_96_p2");
    sc_trace(mVcdFile, tmp_49_i3_fu_66_p3, "tmp_49_i3_fu_66_p3");
#endif

    }
}

p_S0::~p_S0() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void p_S0::thread_ap_ready() {
    ap_ready = ap_const_logic_1;
}

void p_S0::thread_ap_return() {
    ap_return = (tmp_fu_96_p2.read() ^ tmp_49_i3_fu_66_p3.read());
}

void p_S0::thread_tmp_368_fu_40_p1() {
    tmp_368_fu_40_p1 = x.read().range(2-1, 0);
}

void p_S0::thread_tmp_369_fu_62_p1() {
    tmp_369_fu_62_p1 = x.read().range(13-1, 0);
}

void p_S0::thread_tmp_370_fu_84_p1() {
    tmp_370_fu_84_p1 = x.read().range(22-1, 0);
}

void p_S0::thread_tmp_49_i3_fu_66_p3() {
    tmp_49_i3_fu_66_p3 = esl_concat<13,19>(tmp_369_fu_62_p1.read(), tmp_i1_fu_52_p4.read());
}

void p_S0::thread_tmp_49_i6_fu_88_p3() {
    tmp_49_i6_fu_88_p3 = esl_concat<22,10>(tmp_370_fu_84_p1.read(), tmp_i4_fu_74_p4.read());
}

void p_S0::thread_tmp_49_i_fu_44_p3() {
    tmp_49_i_fu_44_p3 = esl_concat<2,30>(tmp_368_fu_40_p1.read(), tmp_i_fu_30_p4.read());
}

void p_S0::thread_tmp_fu_96_p2() {
    tmp_fu_96_p2 = (tmp_49_i_fu_44_p3.read() ^ tmp_49_i6_fu_88_p3.read());
}

void p_S0::thread_tmp_i1_fu_52_p4() {
    tmp_i1_fu_52_p4 = x.read().range(31, 13);
}

void p_S0::thread_tmp_i4_fu_74_p4() {
    tmp_i4_fu_74_p4 = x.read().range(31, 22);
}

void p_S0::thread_tmp_i_fu_30_p4() {
    tmp_i_fu_30_p4 = x.read().range(31, 2);
}

}

