// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _sha256_hash_HH_
#define _sha256_hash_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "p_hash.h"

namespace ap_rtl {

struct sha256_hash : public sc_module {
    // Port declarations 72
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_lv<6> > sha256_buf_address0;
    sc_out< sc_logic > sha256_buf_ce0;
    sc_out< sc_logic > sha256_buf_we0;
    sc_out< sc_lv<8> > sha256_buf_d0;
    sc_in< sc_lv<8> > sha256_buf_q0;
    sc_out< sc_lv<6> > sha256_buf_address1;
    sc_out< sc_logic > sha256_buf_ce1;
    sc_in< sc_lv<8> > sha256_buf_q1;
    sc_out< sc_logic > m_axi_data_AWVALID;
    sc_in< sc_logic > m_axi_data_AWREADY;
    sc_out< sc_lv<32> > m_axi_data_AWADDR;
    sc_out< sc_lv<1> > m_axi_data_AWID;
    sc_out< sc_lv<32> > m_axi_data_AWLEN;
    sc_out< sc_lv<3> > m_axi_data_AWSIZE;
    sc_out< sc_lv<2> > m_axi_data_AWBURST;
    sc_out< sc_lv<2> > m_axi_data_AWLOCK;
    sc_out< sc_lv<4> > m_axi_data_AWCACHE;
    sc_out< sc_lv<3> > m_axi_data_AWPROT;
    sc_out< sc_lv<4> > m_axi_data_AWQOS;
    sc_out< sc_lv<4> > m_axi_data_AWREGION;
    sc_out< sc_lv<1> > m_axi_data_AWUSER;
    sc_out< sc_logic > m_axi_data_WVALID;
    sc_in< sc_logic > m_axi_data_WREADY;
    sc_out< sc_lv<8> > m_axi_data_WDATA;
    sc_out< sc_lv<1> > m_axi_data_WSTRB;
    sc_out< sc_logic > m_axi_data_WLAST;
    sc_out< sc_lv<1> > m_axi_data_WID;
    sc_out< sc_lv<1> > m_axi_data_WUSER;
    sc_out< sc_logic > m_axi_data_ARVALID;
    sc_in< sc_logic > m_axi_data_ARREADY;
    sc_out< sc_lv<32> > m_axi_data_ARADDR;
    sc_out< sc_lv<1> > m_axi_data_ARID;
    sc_out< sc_lv<32> > m_axi_data_ARLEN;
    sc_out< sc_lv<3> > m_axi_data_ARSIZE;
    sc_out< sc_lv<2> > m_axi_data_ARBURST;
    sc_out< sc_lv<2> > m_axi_data_ARLOCK;
    sc_out< sc_lv<4> > m_axi_data_ARCACHE;
    sc_out< sc_lv<3> > m_axi_data_ARPROT;
    sc_out< sc_lv<4> > m_axi_data_ARQOS;
    sc_out< sc_lv<4> > m_axi_data_ARREGION;
    sc_out< sc_lv<1> > m_axi_data_ARUSER;
    sc_in< sc_logic > m_axi_data_RVALID;
    sc_out< sc_logic > m_axi_data_RREADY;
    sc_in< sc_lv<8> > m_axi_data_RDATA;
    sc_in< sc_logic > m_axi_data_RLAST;
    sc_in< sc_lv<1> > m_axi_data_RID;
    sc_in< sc_lv<1> > m_axi_data_RUSER;
    sc_in< sc_lv<2> > m_axi_data_RRESP;
    sc_in< sc_logic > m_axi_data_BVALID;
    sc_out< sc_logic > m_axi_data_BREADY;
    sc_in< sc_lv<2> > m_axi_data_BRESP;
    sc_in< sc_lv<1> > m_axi_data_BID;
    sc_in< sc_lv<1> > m_axi_data_BUSER;
    sc_in< sc_lv<32> > data_offset;
    sc_in< sc_lv<32> > len;
    sc_out< sc_lv<32> > ap_return_0;
    sc_out< sc_lv<32> > ap_return_1;
    sc_out< sc_lv<32> > ap_return_2;
    sc_out< sc_lv<32> > ap_return_3;
    sc_out< sc_lv<32> > ap_return_4;
    sc_out< sc_lv<32> > ap_return_5;
    sc_out< sc_lv<32> > ap_return_6;
    sc_out< sc_lv<32> > ap_return_7;
    sc_out< sc_lv<32> > ap_return_8;
    sc_out< sc_lv<32> > ap_return_9;
    sc_out< sc_lv<32> > ap_return_10;


    // Module declarations
    sha256_hash(sc_module_name name);
    SC_HAS_PROCESS(sha256_hash);

    ~sha256_hash();

    sc_trace_file* mVcdFile;

    p_hash* grp_p_hash_fu_166;
    sc_signal< sc_lv<11> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_logic > data_blk_n_AR;
    sc_signal< sc_logic > data_blk_n_R;
    sc_signal< sc_logic > ap_CS_fsm_state8;
    sc_signal< sc_lv<1> > exitcond_fu_289_p2;
    sc_signal< sc_logic > ap_sig_ioackin_m_axi_data_ARREADY;
    sc_signal< sc_lv<32> > i_1_fu_294_p2;
    sc_signal< sc_lv<32> > i_1_reg_588;
    sc_signal< bool > ap_block_state8;
    sc_signal< sc_lv<8> > data_addr_read_reg_593;
    sc_signal< sc_lv<1> > tmp_3_fu_377_p2;
    sc_signal< sc_lv<1> > tmp_3_reg_598;
    sc_signal< sc_logic > ap_CS_fsm_state9;
    sc_signal< sc_lv<32> > sha256hash_7_load_1_reg_602;
    sc_signal< sc_logic > ap_CS_fsm_state10;
    sc_signal< sc_lv<32> > sha256hash_6_load_1_reg_607;
    sc_signal< sc_lv<32> > sha256hash_5_load_1_reg_612;
    sc_signal< sc_lv<32> > sha256hash_4_load_1_reg_617;
    sc_signal< sc_lv<32> > sha256hash_3_load_1_reg_622;
    sc_signal< sc_lv<32> > sha256hash_2_load_1_reg_627;
    sc_signal< sc_lv<32> > sha256hash_1_load_1_reg_632;
    sc_signal< sc_lv<32> > sha256hash_load_1_reg_637;
    sc_signal< sc_logic > grp_p_hash_fu_166_ap_start;
    sc_signal< sc_logic > grp_p_hash_fu_166_ap_done;
    sc_signal< sc_logic > grp_p_hash_fu_166_ap_idle;
    sc_signal< sc_logic > grp_p_hash_fu_166_ap_ready;
    sc_signal< sc_lv<6> > grp_p_hash_fu_166_sha256_buf_address0;
    sc_signal< sc_logic > grp_p_hash_fu_166_sha256_buf_ce0;
    sc_signal< sc_lv<6> > grp_p_hash_fu_166_sha256_buf_address1;
    sc_signal< sc_logic > grp_p_hash_fu_166_sha256_buf_ce1;
    sc_signal< sc_lv<32> > grp_p_hash_fu_166_ap_return_0;
    sc_signal< sc_lv<32> > grp_p_hash_fu_166_ap_return_1;
    sc_signal< sc_lv<32> > grp_p_hash_fu_166_ap_return_2;
    sc_signal< sc_lv<32> > grp_p_hash_fu_166_ap_return_3;
    sc_signal< sc_lv<32> > grp_p_hash_fu_166_ap_return_4;
    sc_signal< sc_lv<32> > grp_p_hash_fu_166_ap_return_5;
    sc_signal< sc_lv<32> > grp_p_hash_fu_166_ap_return_6;
    sc_signal< sc_lv<32> > grp_p_hash_fu_166_ap_return_7;
    sc_signal< sc_lv<32> > i_reg_155;
    sc_signal< sc_logic > ap_CS_fsm_state7;
    sc_signal< sc_logic > ap_CS_fsm_state11;
    sc_signal< bool > ap_block_state11_on_subcall_done;
    sc_signal< sc_logic > grp_p_hash_fu_166_ap_start_reg;
    sc_signal< sc_lv<64> > tmp_1_fu_366_p1;
    sc_signal< sc_lv<64> > tmp_fu_228_p1;
    sc_signal< sc_logic > ap_reg_ioackin_m_axi_data_ARREADY;
    sc_signal< sc_lv<32> > sha256_len_0_write_s_fu_74;
    sc_signal< sc_lv<32> > sl_fu_371_p2;
    sc_signal< sc_lv<32> > sha256_bits_0_read_s_fu_78;
    sc_signal< sc_lv<32> > sha256_bits_0_write_fu_440_p2;
    sc_signal< sc_lv<32> > sha256hash_7_fu_82;
    sc_signal< sc_lv<32> > sha256hash_6_fu_86;
    sc_signal< sc_lv<32> > sha256hash_5_fu_90;
    sc_signal< sc_lv<32> > sha256hash_4_fu_94;
    sc_signal< sc_lv<32> > sha256hash_3_fu_98;
    sc_signal< sc_lv<32> > sha256hash_2_fu_102;
    sc_signal< sc_lv<32> > sha256hash_1_fu_106;
    sc_signal< sc_lv<32> > sha256hash_fu_110;
    sc_signal< sc_lv<32> > sha256_bits_1_read_s_fu_114;
    sc_signal< sc_lv<32> > tmp_95_read1_i_fu_432_p3;
    sc_signal< sc_lv<1> > tmp_i_fu_420_p2;
    sc_signal< sc_lv<32> > tmp_89_i_fu_426_p2;
    sc_signal< sc_lv<11> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<11> ap_ST_fsm_state1;
    static const sc_lv<11> ap_ST_fsm_state2;
    static const sc_lv<11> ap_ST_fsm_state3;
    static const sc_lv<11> ap_ST_fsm_state4;
    static const sc_lv<11> ap_ST_fsm_state5;
    static const sc_lv<11> ap_ST_fsm_state6;
    static const sc_lv<11> ap_ST_fsm_state7;
    static const sc_lv<11> ap_ST_fsm_state8;
    static const sc_lv<11> ap_ST_fsm_state9;
    static const sc_lv<11> ap_ST_fsm_state10;
    static const sc_lv<11> ap_ST_fsm_state11;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<3> ap_const_lv3_0;
    static const sc_lv<2> ap_const_lv2_0;
    static const sc_lv<4> ap_const_lv4_0;
    static const sc_lv<8> ap_const_lv8_0;
    static const sc_lv<32> ap_const_lv32_7;
    static const sc_lv<32> ap_const_lv32_8;
    static const sc_lv<32> ap_const_lv32_9;
    static const sc_lv<32> ap_const_lv32_6;
    static const sc_lv<32> ap_const_lv32_A;
    static const sc_lv<1> ap_const_lv1_1;
    static const bool ap_const_boolean_0;
    static const sc_lv<32> ap_const_lv32_5BE0CD19;
    static const sc_lv<32> ap_const_lv32_1F83D9AB;
    static const sc_lv<32> ap_const_lv32_9B05688C;
    static const sc_lv<32> ap_const_lv32_510E527F;
    static const sc_lv<32> ap_const_lv32_A54FF53A;
    static const sc_lv<32> ap_const_lv32_3C6EF372;
    static const sc_lv<32> ap_const_lv32_BB67AE85;
    static const sc_lv<32> ap_const_lv32_6A09E667;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<32> ap_const_lv32_FFFFFFBF;
    static const sc_lv<32> ap_const_lv32_40;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state10();
    void thread_ap_CS_fsm_state11();
    void thread_ap_CS_fsm_state7();
    void thread_ap_CS_fsm_state8();
    void thread_ap_CS_fsm_state9();
    void thread_ap_block_state11_on_subcall_done();
    void thread_ap_block_state8();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_ap_return_0();
    void thread_ap_return_1();
    void thread_ap_return_10();
    void thread_ap_return_2();
    void thread_ap_return_3();
    void thread_ap_return_4();
    void thread_ap_return_5();
    void thread_ap_return_6();
    void thread_ap_return_7();
    void thread_ap_return_8();
    void thread_ap_return_9();
    void thread_ap_sig_ioackin_m_axi_data_ARREADY();
    void thread_data_blk_n_AR();
    void thread_data_blk_n_R();
    void thread_exitcond_fu_289_p2();
    void thread_grp_p_hash_fu_166_ap_start();
    void thread_i_1_fu_294_p2();
    void thread_m_axi_data_ARADDR();
    void thread_m_axi_data_ARBURST();
    void thread_m_axi_data_ARCACHE();
    void thread_m_axi_data_ARID();
    void thread_m_axi_data_ARLEN();
    void thread_m_axi_data_ARLOCK();
    void thread_m_axi_data_ARPROT();
    void thread_m_axi_data_ARQOS();
    void thread_m_axi_data_ARREGION();
    void thread_m_axi_data_ARSIZE();
    void thread_m_axi_data_ARUSER();
    void thread_m_axi_data_ARVALID();
    void thread_m_axi_data_AWADDR();
    void thread_m_axi_data_AWBURST();
    void thread_m_axi_data_AWCACHE();
    void thread_m_axi_data_AWID();
    void thread_m_axi_data_AWLEN();
    void thread_m_axi_data_AWLOCK();
    void thread_m_axi_data_AWPROT();
    void thread_m_axi_data_AWQOS();
    void thread_m_axi_data_AWREGION();
    void thread_m_axi_data_AWSIZE();
    void thread_m_axi_data_AWUSER();
    void thread_m_axi_data_AWVALID();
    void thread_m_axi_data_BREADY();
    void thread_m_axi_data_RREADY();
    void thread_m_axi_data_WDATA();
    void thread_m_axi_data_WID();
    void thread_m_axi_data_WLAST();
    void thread_m_axi_data_WSTRB();
    void thread_m_axi_data_WUSER();
    void thread_m_axi_data_WVALID();
    void thread_sha256_bits_0_write_fu_440_p2();
    void thread_sha256_buf_address0();
    void thread_sha256_buf_address1();
    void thread_sha256_buf_ce0();
    void thread_sha256_buf_ce1();
    void thread_sha256_buf_d0();
    void thread_sha256_buf_we0();
    void thread_sl_fu_371_p2();
    void thread_tmp_1_fu_366_p1();
    void thread_tmp_3_fu_377_p2();
    void thread_tmp_89_i_fu_426_p2();
    void thread_tmp_95_read1_i_fu_432_p3();
    void thread_tmp_fu_228_p1();
    void thread_tmp_i_fu_420_p2();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
