// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module p_Ch (
        ap_ready,
        x,
        y,
        z,
        ap_return
);


output   ap_ready;
input  [31:0] x;
input  [31:0] y;
input  [31:0] z;
output  [31:0] ap_return;

wire   [31:0] tmp_s_fu_34_p2;
wire   [31:0] tmp_41_fu_40_p2;
wire   [31:0] tmp_fu_28_p2;

assign ap_ready = 1'b1;

assign ap_return = (tmp_fu_28_p2 ^ tmp_41_fu_40_p2);

assign tmp_41_fu_40_p2 = (z & tmp_s_fu_34_p2);

assign tmp_fu_28_p2 = (y & x);

assign tmp_s_fu_34_p2 = (x ^ 32'd4294967295);

endmodule //p_Ch
