// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module p_G1 (
        ap_ready,
        x,
        ap_return
);


output   ap_ready;
input  [31:0] x;
output  [31:0] ap_return;

wire   [16:0] tmp_371_fu_38_p1;
wire   [14:0] tmp_i_fu_28_p4;
wire   [18:0] tmp_372_fu_60_p1;
wire   [12:0] tmp_i1_fu_50_p4;
wire   [21:0] tmp_s_fu_72_p4;
wire   [31:0] tmp_38_fu_82_p1;
wire   [31:0] tmp_49_i3_fu_64_p3;
wire   [31:0] tmp_fu_86_p2;
wire   [31:0] tmp_49_i_fu_42_p3;

assign ap_ready = 1'b1;

assign ap_return = (tmp_fu_86_p2 ^ tmp_49_i_fu_42_p3);

assign tmp_371_fu_38_p1 = x[16:0];

assign tmp_372_fu_60_p1 = x[18:0];

assign tmp_38_fu_82_p1 = tmp_s_fu_72_p4;

assign tmp_49_i3_fu_64_p3 = {{tmp_372_fu_60_p1}, {tmp_i1_fu_50_p4}};

assign tmp_49_i_fu_42_p3 = {{tmp_371_fu_38_p1}, {tmp_i_fu_28_p4}};

assign tmp_fu_86_p2 = (tmp_49_i3_fu_64_p3 ^ tmp_38_fu_82_p1);

assign tmp_i1_fu_50_p4 = {{x[31:19]}};

assign tmp_i_fu_28_p4 = {{x[31:17]}};

assign tmp_s_fu_72_p4 = {{x[31:10]}};

endmodule //p_G1
