// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module p_G0 (
        ap_ready,
        x,
        ap_return
);


output   ap_ready;
input  [31:0] x;
output  [31:0] ap_return;

wire   [6:0] tmp_373_fu_38_p1;
wire   [24:0] tmp_i_fu_28_p4;
wire   [17:0] tmp_374_fu_60_p1;
wire   [13:0] tmp_i1_fu_50_p4;
wire   [28:0] tmp_s_fu_72_p4;
wire   [31:0] tmp_41_fu_82_p1;
wire   [31:0] tmp_49_i3_fu_64_p3;
wire   [31:0] tmp_fu_86_p2;
wire   [31:0] tmp_49_i_fu_42_p3;

assign ap_ready = 1'b1;

assign ap_return = (tmp_fu_86_p2 ^ tmp_49_i_fu_42_p3);

assign tmp_373_fu_38_p1 = x[6:0];

assign tmp_374_fu_60_p1 = x[17:0];

assign tmp_41_fu_82_p1 = tmp_s_fu_72_p4;

assign tmp_49_i3_fu_64_p3 = {{tmp_374_fu_60_p1}, {tmp_i1_fu_50_p4}};

assign tmp_49_i_fu_42_p3 = {{tmp_373_fu_38_p1}, {tmp_i_fu_28_p4}};

assign tmp_fu_86_p2 = (tmp_49_i3_fu_64_p3 ^ tmp_41_fu_82_p1);

assign tmp_i1_fu_50_p4 = {{x[31:18]}};

assign tmp_i_fu_28_p4 = {{x[31:7]}};

assign tmp_s_fu_72_p4 = {{x[31:3]}};

endmodule //p_G0
