# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/My_File/study/SHA256-FPGA-HLS/sha256_prj/sha256_prj.srcs/sources_1/bd/design_1/ip/design_1_sha256_0_0/design_1_sha256_0_0.xci
# IP: The module: 'design_1_sha256_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/My_File/study/SHA256-FPGA-HLS/sha256_prj/sha256_prj.srcs/sources_1/bd/design_1/ip/design_1_sha256_0_0/constraints/sha256_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_sha256_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: e:/My_File/study/SHA256-FPGA-HLS/sha256_prj/sha256_prj.srcs/sources_1/bd/design_1/ip/design_1_sha256_0_0/design_1_sha256_0_0.xci
# IP: The module: 'design_1_sha256_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/My_File/study/SHA256-FPGA-HLS/sha256_prj/sha256_prj.srcs/sources_1/bd/design_1/ip/design_1_sha256_0_0/constraints/sha256_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_sha256_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
